FROM node
# Front-end
EXPOSE 3000
EXPOSE 3001
EXPOSE 3002

# Back-end
EXPOSE 8082
EXPOSE 8081
EXPOSE 8080
# Guardian
EXPOSE 3010
WORKDIR /next
RUN npm init -y
RUN npm install next --save

WORKDIR /app
