apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-tymlez-service.fullname" . }}-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
  MQ_ADDRESS: {{ .Release.Name }}-guardian-message-broker-{{ .Release.Revision }}
  MONGO_DB_CONNECTION: mongodb://{{ .Release.Name }}-mongodb:27017/tymlez_db
  MRV_RECEIVER_URL: http://{{ .Release.Name }}-guardian-message-broker-{{ .Release.Revision }}:3003/mrv
  GUARDIAN_API_GW_URL: http://{{ .Release.Name }}-guardian-web-proxy:80/api/v1
  GUARDIAN_SERVICE_BASE_URL: http://{{ .Release.Name }}-guardian-web-proxy:80
  MESSAGE_BROKER_BASE_URL: http://{{ .Release.Name }}-guardian-message-broker-{{ .Release.Revision }}:3003
